import { skillDetails } from "./skill-details.js";

const launchSkills = [
  {
    slug: "design-audit",
    name: "Design Audit",
    category: "Design",
    launchDate: "Apr 30, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2049882721032233347",
    headline: "See exactly what is holding your interface back.",
    description: "Audit a website or frontend for visual hierarchy, UX, responsiveness, accessibility, and polish.",
  },
  {
    slug: "video-short-maker",
    name: "Video Short Maker",
    category: "Media",
    launchDate: "May 1, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2050251401348165809",
    headline: "Turn a long video into a sharp short.",
    description: "Trim dead air, cut the strongest moments, and optionally add local Whisper subtitles with ffmpeg.",
  },
  {
    slug: "startup-pressure-test",
    name: "Startup Pressure Test",
    category: "Startup",
    launchDate: "May 3, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2050908233158816122",
    headline: "Find the flaws before you build.",
    description: "Pressure-test a startup idea, expose its core assumptions, and define the smallest useful validation.",
  },
  {
    slug: "codex-fm",
    name: "Codex FM",
    category: "Productivity",
    launchDate: "May 8, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2052811648813892021",
    headline: "Put the Codex lo-fi radio on.",
    description: "Launch a pixel-art lo-fi radio built for long Codex sessions and quiet focus.",
  },
  {
    slug: "codex-pomodoro-arena",
    name: "Pomodoro Arena",
    category: "Productivity",
    launchDate: "May 9, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2053082556028026897",
    headline: "Turn a focus session into a boss fight.",
    description: "Launch a Codex-themed Pomodoro arena that makes focused work feel like a game.",
  },
  {
    slug: "simple-flight-search",
    name: "Cheap Flights",
    category: "Research",
    launchDate: "May 11, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2053822430339375517",
    headline: "Find a better flight without a scraping stack.",
    description: "Collect current flight options from public search pages and compare prices, dates, stops, and baggage hints.",
  },
  {
    slug: "local-client-prospector",
    name: "Local Client Prospector",
    category: "Growth",
    launchDate: "May 14, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2054981327414231173",
    headline: "Find local businesses that actually need a website.",
    description: "Research and qualify nearby businesses with weak or missing websites and produce a practical lead sheet.",
  },
  {
    slug: "complexity-optimizer",
    name: "Complexity Optimizer",
    category: "Build",
    launchDate: "May 15, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2055343704467206506",
    headline: "Find the expensive code before it becomes a problem.",
    description: "Locate algorithmic complexity and performance hotspots, then propose safe, behavior-preserving improvements.",
  },
  {
    slug: "visual-web-builder",
    name: "Visual Web Builder",
    category: "Design",
    launchDate: "May 18, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2056344054938628218",
    headline: "Generate the visual. Then build the real website.",
    description: "Combine image generation with an image-first frontend workflow for polished, implementation-ready websites.",
  },
  {
    slug: "site-post-screenshots",
    name: "Site Post Screenshots",
    category: "Media",
    launchDate: "May 19, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2056706439360442462",
    headline: "Turn a live website into four launch-ready visuals.",
    description: "Capture faithful desktop, mobile, X, and desktop-plus-phone screenshots without redesigning the site.",
  },
  {
    slug: "x-phoenix-score",
    name: "X Phoenix Score",
    category: "Growth",
    launchDate: "May 21, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2057509200603775052",
    headline: "See how an X post is likely to perform before publishing.",
    description: "Score and improve X posts using engagement signals derived from the open-source X algorithm references.",
  },
  {
    slug: "goal-mvp",
    name: "Goal MVP",
    category: "Startup",
    launchDate: "May 23, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2058155994291548537",
    headline: "Turn an idea into a working MVP.",
    description: "Scope, plan, build, verify, and launch the smallest version of an idea that can prove real value.",
    featured: true,
  },
  {
    slug: "codex-phone-lab",
    name: "Phone Lab",
    category: "Build",
    launchDate: "May 24, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2058578772585074958",
    headline: "Build and test an app on a real phone.",
    description: "Create React Native apps with an Expo live preview that runs directly on a physical iPhone or Android device.",
  },
  {
    slug: "mac-storage-cleanup",
    name: "Mac Storage Cleanup",
    category: "System",
    launchDate: "May 27, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2059605538670051727",
    headline: "Find what is wasting space on your Mac.",
    description: "Audit large caches, logs, downloads, simulators, build artifacts, and development leftovers before removing anything.",
  },
  {
    slug: "name-prospector",
    name: "Name Prospector",
    category: "Startup",
    launchDate: "May 28, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2059967933389119981",
    headline: "Generate more names. Keep only the defensible ones.",
    description: "Generate brand names at scale, check likely domains, and surface competitors using similar identities.",
  },
  {
    slug: "codex-security-audit-skill",
    name: "Security Audit",
    category: "Security",
    launchDate: "Jun 4, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2062504650163839254",
    headline: "Find the security risks before launch.",
    description: "Audit applications for exposed secrets, unsafe authentication, authorization bugs, dependency risk, and insecure input handling.",
  },
  {
    slug: "sell-my-saas",
    name: "Sell My SaaS",
    category: "Growth",
    launchDate: "Jun 5, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2062867038939562369",
    headline: "Turn a product into sales content people will actually read.",
    description: "Create launch posts, cold DMs, founder updates, and platform-specific sales copy from a product URL.",
  },
  {
    slug: "mengtofrontend",
    name: "MengTo Frontend",
    category: "Design",
    launchDate: "Jun 6, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2063229427044241879",
    headline: "Remove the visual tells that make a landing page feel AI-made.",
    description: "Audit and refine typography, spacing, imagery, interaction, and finishing details using Meng To's design checklist.",
  },
  {
    slug: "landing-to-powerpoint",
    name: "Landing to PowerPoint",
    category: "Media",
    launchDate: "Jun 8, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2063954193644396567",
    headline: "Turn a landing page into a polished presentation.",
    description: "Transform a live URL or local landing page into a concise PowerPoint deck with a matching PDF and preview.",
  },
  {
    slug: "startup-user-simulator",
    name: "Startup User Simulator",
    category: "Startup",
    launchDate: "Jul 12, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2076275381305233478",
    headline: "See why five plausible customers would convert or leave.",
    description: "Simulate how realistic customer personas experience a startup, product, or landing page and rank the conversion friction.",
  },
  {
    slug: "first-customer-finder",
    name: "First Customer Finder",
    category: "Growth",
    launchDate: "Jul 13, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2076637778734153857",
    headline: "Find the people who already need what you are building.",
    description: "Find evidence-backed early adopters using recent public pain, buying signals, and active workarounds.",
  },
  {
    slug: "startup-channel-finder",
    name: "Startup Channel Finder",
    category: "Growth",
    launchDate: "Jul 18, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2078464813429367277",
    headline: "Launch where the right people are already paying attention.",
    description: "Research, rank, and plan the best current channels for launching a startup, SaaS, or developer tool.",
  },
  {
    slug: "startup-pricing-lab",
    name: "Startup Pricing Lab",
    category: "Startup",
    launchDate: "Jul 19, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2078812095462900047",
    headline: "Price your product with evidence.",
    description: "Compare monetization models, current market anchors, value metrics, and reversible pricing hypotheses.",
  },
  {
    slug: "startup-business-planner",
    name: "Startup Business Planner",
    category: "Startup",
    launchDate: "Jul 20, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2079189588807954498",
    headline: "Turn a product idea into an operating business plan.",
    description: "Build an evidence-backed business plan, monetization architecture, financial model, and 90-day execution roadmap.",
  },
  {
    slug: "code-rot-cleaner",
    name: "Code Rot Cleaner",
    category: "Build",
    launchDate: "Jul 21, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2079551973339349170",
    headline: "Find the code your project may no longer need.",
    description: "Separate credible dead-code evidence from framework false positives and prove safe cleanup candidates.",
  },
  {
    slug: "mac-file-detective",
    name: "Mac File Detective",
    category: "System",
    launchDate: "Jul 22, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2079914364899881091",
    headline: "Find the file you remember but cannot locate.",
    description: "Combine Spotlight, filenames, document text, dates, metadata, and previews to recover forgotten local files.",
  },
  {
    slug: "build-startup-brand",
    name: "Build Startup Brand",
    category: "Design",
    launchDate: "Jul 26, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2081348810824159442",
    headline: "Turn a startup idea into a distinctive brand system.",
    description: "Create positioning, voice, messaging, visual territories, palette, typography, and compact brand guidelines.",
  },
  {
    slug: "startup-launch-doctor",
    name: "Startup Launch Doctor",
    category: "Startup",
    launchDate: "Jul 28, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2082073596856607075",
    headline: "Find what will hurt the launch before launch day.",
    description: "Audit positioning, product proof, trust, UX, accessibility, broken paths, and operational readiness.",
  },
  {
    slug: "analyze-startup-feedback",
    name: "Startup Feedback Engine",
    category: "Research",
    launchDate: "Aug 2, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2083957246674042890",
    headline: "Turn scattered feedback into product evidence.",
    description: "Cluster customer feedback, trace recurring pains, rank opportunities, and preserve credible customer language.",
  },
  {
    slug: "track-startup-competitors",
    name: "Startup Competitor Radar",
    category: "Research",
    launchDate: "Aug 5, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2084972696237183197",
    headline: "Track what competitors changed and why it matters.",
    description: "Monitor pricing, product pages, changelogs, repositories, public posts, news, and market positioning.",
  },
  {
    slug: "simulate-startup-sales",
    name: "Startup Sales Simulator",
    category: "Growth",
    launchDate: "Aug 7, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2085697476556738723",
    headline: "Practice the sales call before the real buyer arrives.",
    description: "Run realistic buyer role-plays, objections, multi-call stakeholder scenarios, and evidence-linked performance reviews.",
  },
  {
    slug: "generate-startup-ideas",
    name: "Startup Idea Machine",
    category: "Startup",
    launchDate: "Aug 11, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2087147021585232334",
    headline: "Generate startup ideas that match the founder and the market.",
    description: "Rapidly generate, refine, research, compare, and validate founder-specific startup opportunities.",
  },
  {
    slug: "code-change-guardian",
    name: "Code Change Guardian",
    category: "Build",
    launchDate: "Aug 14, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2088234180429627780",
    headline: "Know what a code change can break before you ship it.",
    description: "Map blast radius, preserve behavior, characterize implicit contracts, and prove refactors with repository evidence.",
  },
  {
    slug: "app-store-review-guardian",
    name: "App Store Review Guardian",
    category: "Build",
    launchDate: "Aug 17, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2089321345482179027",
    headline: "Ship to the App Store with fewer surprises.",
    description: "Audit privacy, permissions, payments, authentication, reviewer access, and common App Review risks.",
  },
  {
    slug: "create-product-ads-with-actionway",
    name: "Actionway Product Ad Creator",
    category: "Media",
    launchDate: "Aug 24, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2091933561192386882",
    headline: "Turn a product screenshot into a finished video ad.",
    description: "Create a short product advertisement with video, voiceover, optional music, and a platform-ready MP4.",
  },
  {
    slug: "codex-first-million",
    name: "Path to First Million",
    category: "Finance",
    launchDate: "Aug 27, 2026",
    xUrl: "https://x.com/Kappaemmedev/status/2093020717969261020",
    headline: "Map a realistic path toward the first million.",
    description: "Build an assumption-driven wealth roadmap with scenarios, milestones, income levers, and an actionable plan.",
  },
];

const githubRepositories = {
  "design-audit": "codex-design-audit-skill",
  "video-short-maker": "codex-video-short-maker-skill",
  "startup-pressure-test": "codex-startup-pressure-test-skill",
  "codex-fm": "codex-fm",
  "codex-pomodoro-arena": "codex-pomodoro-arena",
  "simple-flight-search": "codex-simple-flight-search-skill",
  "local-client-prospector": "local-client-prospector-skill",
  "complexity-optimizer": "codex-complexity-optimizer",
  "site-post-screenshots": "site-post-screenshots",
  "x-phoenix-score": "x-phoenix-score-codex-skill",
  "goal-mvp": "codex-mvp-goal-skill",
  "codex-phone-lab": "codex-phone-lab",
  "mac-storage-cleanup": "codex-mac-storage-cleanup",
  "codex-security-audit-skill": "codex-security-audit-skill",
  "sell-my-saas": "codex-sell-my-saas-skill",
  "mengtofrontend": "MengToFrontend",
  "landing-to-powerpoint": "landing-to-powerpoint",
  "startup-user-simulator": "codex-startup-user-simulator-skill",
  "first-customer-finder": "codex-first-customer-finder-skill",
  "startup-channel-finder": "codex-startup-channel-finder",
  "startup-pricing-lab": "codex-startup-pricing-lab",
  "startup-business-planner": "codex-startup-business-planner",
  "code-rot-cleaner": "codex-code-rot-cleaner",
  "mac-file-detective": "codex-mac-file-detective",
  "build-startup-brand": "build-startup-brand",
  "startup-launch-doctor": "startup-launch-doctor",
  "analyze-startup-feedback": "startup-feedback-engine",
  "track-startup-competitors": "startup-competitor-radar",
  "simulate-startup-sales": "startup-sales-simulator",
  "generate-startup-ideas": "startup-idea-machine",
  "code-change-guardian": "code-change-guardian",
  "app-store-review-guardian": "app-store-review-guardian",
  "create-product-ads-with-actionway": "actionway-product-ad-creator",
  "codex-first-million": "codex-first-million",
};

const installationCommands = {
  "design-audit": "npx codex-design-audit-skill",
  "video-short-maker": "npx --yes codex-video-short-maker-skill@latest",
  "startup-pressure-test": "npx --yes codex-startup-pressure-test-skill@latest",
  "codex-fm": "npx codex-fm",
  "codex-pomodoro-arena": "npx --yes codex-pomodoro-arena@latest --install-skill",
  "simple-flight-search": "npx codex-simple-flight-search-skill",
  "local-client-prospector": "npx local-client-prospector-skill",
  "complexity-optimizer": "npx codex-complexity-optimizer",
  "visual-web-builder": "npx codex-visual-web-builder",
  "site-post-screenshots": "npx site-post-screenshots",
  "x-phoenix-score": "npx x-phoenix-score-codex-skill",
  "goal-mvp": "npx codex-goal-mvp-skill",
  "codex-phone-lab": "npx --yes codex-phone-lab",
  "mac-storage-cleanup": "npx codex-mac-storage-cleanup@latest",
  "name-prospector": "npx name-prospector-skill",
  "codex-security-audit-skill": "npx codex-security-audit-skill",
  "sell-my-saas": "npx codex-sell-my-saas-skill",
  "mengtofrontend": "npx mengtofrontend",
  "landing-to-powerpoint": "npx --yes landing-to-powerpoint@latest",
  "startup-user-simulator": "npx --yes codex-startup-user-simulator-skill@latest",
  "first-customer-finder": "npx --yes codex-first-customer-finder-skill@latest",
  "startup-channel-finder": "npx --yes codex-startup-channel-finder@latest",
  "startup-pricing-lab": "npx --yes codex-startup-pricing-lab@latest",
  "startup-business-planner": "npx --yes codex-startup-business-planner@latest",
  "code-rot-cleaner": "npx --yes codex-code-rot-cleaner@latest",
  "mac-file-detective": "npx --yes codex-mac-file-detective@latest",
  "build-startup-brand": "npx --yes build-startup-brand@latest",
  "startup-launch-doctor": "npx --yes startup-launch-doctor@latest",
  "analyze-startup-feedback": "npx --yes startup-feedback-engine@latest",
  "track-startup-competitors": "npx --yes startup-competitor-radar@latest",
  "simulate-startup-sales": "npx --yes startup-sales-simulator@latest",
  "generate-startup-ideas": "npx --yes startup-idea-machine@latest",
  "code-change-guardian": "npx --yes codex-code-change-guardian@latest",
  "app-store-review-guardian": "npx --yes codex-app-store-review-guardian@latest",
  "create-product-ads-with-actionway": "npx skills add Kappaemme-git/actionway-product-ad-creator -g -y --skill create-product-ads-with-actionway --agent codex",
  "codex-first-million": "npx --yes codex-first-million@latest",
};

const portableAgents = ["Codex", "Claude Code", "Cursor", "OpenCode"];
const codexDependentSkills = new Set([
  "codex-fm",
  "codex-pomodoro-arena",
  "visual-web-builder",
  "site-post-screenshots",
  "codex-phone-lab",
  "landing-to-powerpoint",
  "create-product-ads-with-actionway",
]);

const gregPosts = {
  "analyze-startup-feedback": "https://x.com/gdb/status/2084074129930772953",
  "first-customer-finder": "https://x.com/gdb/status/2076686329686171666",
  "complexity-optimizer": "https://x.com/gdb/status/2055646916499714488",
  "local-client-prospector": "https://x.com/gdb/status/2055285857628676399",
  "startup-pressure-test": "https://x.com/gdb/status/2050972114077843772",
};

const categoryOutcomes = {
  Build: [
    "Inspects the real project before proposing changes.",
    "Executes a focused workflow with explicit boundaries.",
    "Verifies the result against the repository's actual behavior.",
  ],
  Startup: [
    "Turns a broad startup question into a concrete decision.",
    "Uses evidence and explicit assumptions instead of startup theatre.",
    "Ends with the smallest useful next experiment.",
  ],
  Growth: [
    "Defines the audience and outcome before producing tactics.",
    "Finds traceable signals instead of inventing demand.",
    "Produces an actionable distribution or sales output.",
  ],
  Design: [
    "Establishes a clear visual or evaluative direction.",
    "Preserves hierarchy, spacing, typography, and interaction quality.",
    "Finishes with a result that can be inspected and refined.",
  ],
  Research: [
    "Collects current, attributable evidence.",
    "Separates observations from assumptions and inference.",
    "Returns a concise comparison or decision-ready report.",
  ],
  System: [
    "Starts with a scoped, read-only inspection.",
    "Explains why every candidate matters before changing anything.",
    "Keeps risky actions explicit and recoverable.",
  ],
  Media: [
    "Starts from real source material instead of a fake mockup.",
    "Produces a consistent, platform-ready visual output.",
    "Verifies the final media before delivery.",
  ],
  Productivity: [
    "Creates a focused environment for the work at hand.",
    "Keeps the interaction lightweight and immediately usable.",
    "Makes the result easy to launch again later.",
  ],
  Security: [
    "Maps the exposed surface before ranking findings.",
    "Prioritizes practical risks with repository evidence.",
    "Produces an actionable remediation order.",
  ],
  Finance: [
    "Makes every assumption visible and editable.",
    "Compares realistic scenarios instead of promising outcomes.",
    "Turns the model into concrete milestones and actions.",
  ],
};

export const skills = launchSkills.map((skill) => ({
  ...skill,
  ...skillDetails[skill.slug],
  agents: codexDependentSkills.has(skill.slug) ? ["Codex"] : portableAgents,
  portable: !codexDependentSkills.has(skill.slug),
  gregPostUrl: gregPosts[skill.slug] ?? null,
  repositoryName: githubRepositories[skill.slug] ?? null,
  githubUrl: githubRepositories[skill.slug]
    ? `https://github.com/Kappaemme-git/${githubRepositories[skill.slug]}`
    : null,
  command: installationCommands[skill.slug],
  kicker: `Released on X · ${skill.launchDate}`,
  detail: skillDetails[skill.slug]?.overview ?? skill.description,
  outcomes: skillDetails[skill.slug]?.useCases ?? categoryOutcomes[skill.category],
  coverImage: `/skill-covers/${skill.slug}.png?v=20260828`,
}));

export const categories = [
  "All",
  "Build",
  "Startup",
  "Growth",
  "Design",
  "Research",
  "System",
  "Media",
  "Productivity",
  "Security",
  "Finance",
];

export const agents = ["All agents", ...portableAgents];
